export const Actions =  {
  GO_FIRST: 'GO_FIRST',
  GO_PREVIOUS: 'GO_PREVIOUS',
  GO_NEXT: 'GO_NEXT',
  GO_LAST: 'GO_LAST',
  GO: 'GO',
  GO_TO_PAGE: 'GO_TO_PAGE',
  CHANGE_PAGE_SIZE: 'CHANGE_PAGE_SIZE',
  SET_COUNT_LAST_PAGE: 'SET_COUNT_LAST_PAGE',
  BUILD_LIST: 'BUILD_LIST',
  SET_PATH: 'SET_PATH',
  ADD_FILTER: 'ADD_FILTER',
  SET_OPTION_STATE: 'SET_OPTION_STATE',
  PERFIS_FETCHED: 'PERFIS_FETCHED',
  ESCALA_TIPOS_FETCHED: 'ESCALA_TIPOS_FETCHED',
  AREA_ORGANIZACIONALS_FETCHED: 'AREA_ORGANIZACIONALS_FETCHED',
  ESCALAS_FETCHED: 'ESCALAS_FETCHED',
  PESSOAS_FETCHED: 'PESSOAS_FETCHED',
  VIATURAS_FETCHED: 'VIATURAS_FETCHED',
  ARMAS_FETCHED: 'ARMAS_FETCHED',
  ITEMS_FETCHED: 'ITEMS_FETCHED',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  DROGA_APREENDIDA_UNIDADES_FETCHED: 'DROGA_APREENDIDA_UNIDADES_FETCHED',
  DROGA_APREENDIDA_TIPOS_FETCHED: 'DROGA_APREENDIDA_TIPOS_FETCHED',
  OPERACAO_STATUS_FETCHED: 'OPERACAO_STATUS_FETCHED',
  SIDEBAR_MINIMIZED: 'SIDEBAR_MINIMIZED',
  SIDEBAR_HIDDEN: 'SIDEBAR_HIDDEN',
  VIATURA_FETCHED : 'VIATURA_FETCHED',
  POLYLINE_UPDATED : 'POLYLINE_UPDATED',
  AFASTAMENTO_TIPO_FETCHED: 'AFASTAMENTO_TIPO_FETCHED'
}

export const EscalaActions = {
  LOAD_AREA_ORGANIZACIONALS: 'LOAD_AREA_ORGANIZACIONALS',
  SELECT_AREA_ORGANIZACIONALS: 'SELECT_AREA_ORGANIZACIONALS',

  LOAD_AGENTES: 'LOAD_AGENTES',

  ADD_TO_AGENTES: 'ADD_TO_AGENTES',
  SELECT_AGENTES: 'SELECT_AGENTES',
  UPDATE_AGENTES: 'UPDATE_AGENTES',

 // REMOVE_AGENTES_OPTIONS: 'REMOVE_AGENTES_OPTIONS',

  ADD_TO_TURNO1: 'ADD_TO_TURNO1',
  ADD_TO_TURNO2: 'ADD_TO_TURNO2',
  ADD_TO_TURNO3: 'ADD_TO_TURNO3',
  ADD_TO_TURNO4: 'ADD_TO_TURNO4',

  SELECT_TURNO1: 'SELECT_TURNO1',
  SELECT_TURNO2: 'SELECT_TURNO2',
  SELECT_TURNO3: 'SELECT_TURNO3',
  SELECT_TURNO4: 'SELECT_TURNO4',

  UPDATE_TURNO1: 'UPDATE_TURNO1',
  UPDATE_TURNO2: 'UPDATE_TURNO2',
  UPDATE_TURNO3: 'UPDATE_TURNO3',
  UPDATE_TURNO4: 'UPDATE_TURNO4',





}


