package com.moveltrack.cartaoprograma.model;
// Generated 23/07/2018 04:54:41 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AfinidadeId generated by hbm2java
 */
@Embeddable
public class AfinidadeId implements java.io.Serializable {

	private Integer afinidadeId;
	private Integer pessoaId;

	public AfinidadeId() {
	}

	public AfinidadeId(Integer afinidadeId, Integer pessoaId) {
		this.afinidadeId = afinidadeId;
		this.pessoaId = pessoaId;
	}

	@Column(name = "afinidade_id")
	public Integer getAfinidadeId() {
		return this.afinidadeId;
	}

	public void setAfinidadeId(Integer afinidadeId) {
		this.afinidadeId = afinidadeId;
	}

	@Column(name = "pessoa_id")
	public Integer getPessoaId() {
		return this.pessoaId;
	}

	public void setPessoaId(Integer pessoaId) {
		this.pessoaId = pessoaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AfinidadeId))
			return false;
		AfinidadeId castOther = (AfinidadeId) other;

		return ((this.getAfinidadeId() == castOther.getAfinidadeId()) || (this.getAfinidadeId() != null
				&& castOther.getAfinidadeId() != null && this.getAfinidadeId().equals(castOther.getAfinidadeId())))
				&& ((this.getPessoaId() == castOther.getPessoaId()) || (this.getPessoaId() != null
						&& castOther.getPessoaId() != null && this.getPessoaId().equals(castOther.getPessoaId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAfinidadeId() == null ? 0 : this.getAfinidadeId().hashCode());
		result = 37 * result + (getPessoaId() == null ? 0 : this.getPessoaId().hashCode());
		return result;
	}

}
