package com.moveltrack.cartaoprograma.model;
// Generated 23/07/2018 04:54:41 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * DrogaApreendida generated by hbm2java
 */
@Entity
public class DrogaApreendida implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(columnDefinition="serial")
	private Integer id;
	
	
	private Integer quantidade;
	
    @NotNull
    @Enumerated(EnumType.STRING)
	private DrogaApreendidaUnidade unidade;
    
    @NotNull
    @Enumerated(EnumType.STRING)
	private DrogaApreendidaTipo tipo;

	
	private String observacoes;
	
	@JsonIgnore
	@ManyToOne
	private Operacao operacao;
	
	public Operacao getOperacao() {
		return operacao;
	}
	public void setOperacao(Operacao operacao) {
		this.operacao = operacao;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	public DrogaApreendidaTipo getTipo() {
		return tipo;
	}
	public void setTipo(DrogaApreendidaTipo tipo) {
		this.tipo = tipo;
	}
	public Integer getQuantidade() {
		return quantidade;
	}
	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}
	
	public DrogaApreendidaUnidade getUnidade() {
		return unidade;
	}
	public void setUnidade(DrogaApreendidaUnidade unidade) {
		this.unidade = unidade;
	}
	public String getObservacoes() {
		return observacoes;
	}
	public void setObservacoes(String observacoes) {
		this.observacoes = observacoes;
	}


}
