package com.moveltrack.cartaoprograma.model;
// Generated 23/07/2018 04:54:41 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;

/**
 * Arma generated by hbm2java
 */
@Entity
@IdClass(EquipamentoDeApoioID.class)
public class EquipamentoDeApoio implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	

	@Id
	private String descricao;
	
	@Id
	private Integer operacaoId;
	

	private Integer quantidade;

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Integer getOperacaoId() {
		return operacaoId;
	}

	public void setOperacaoId(Integer operacaoId) {
		this.operacaoId = operacaoId;
	}

	public Integer getQuantidade() {
		return quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	
	

}
