package com.moveltrack.cartaoprograma.model;
// Generated 23/07/2018 04:54:41 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * AreaOrganizacional generated by hbm2java
 */
@Entity
public class EscalaEquipe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(columnDefinition="serial")
	private int id;
	
    @Enumerated(EnumType.STRING)
	private EscalaEquipeSigla sigla;

    @ManyToOne
    private AreaOrganizacional areaOrganizacional;

    @OneToOne
	private Pessoa pessoa;



	public int getId() {
		return id;
	}


	public void setId(int id) {
		this.id = id;
	}


	public EscalaEquipeSigla getSigla() {
		return sigla;
	}


	public void setSigla(EscalaEquipeSigla sigla) {
		this.sigla = sigla;
	}


	public Pessoa getPessoa() {
		return pessoa;
	}


	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}


	public AreaOrganizacional getAreaOrganizacional() {
		return areaOrganizacional;
	}


	public void setAreaOrganizacional(AreaOrganizacional areaOrganizacional) {
		this.areaOrganizacional = areaOrganizacional;
	}
	

	
	
}
