package com.moveltrack.cartaoprograma.model;
// Generated 23/07/2018 04:54:41 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * AreaOrganizacional generated by hbm2java
 */
@Entity
public class Escala implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(columnDefinition="serial")
	private int id;
	
    @ManyToOne
    private AreaOrganizacional areaOrganizacional;
    
    
    @ManyToOne
    //@JoinColumn(columnDefinition="integer", name="escala_tipo_id")
    private EscalaTipo escalaTipo;
    


	private Integer ano;
	
	private Integer mes;
	
	private Integer rendicaoHora;
	private Integer rendicaoMinuto;

	public Integer getRendicaoHora() {
		return rendicaoHora;
	}

	public void setRendicaoHora(Integer rendicaoHora) {
		this.rendicaoHora = rendicaoHora;
	}

	public Integer getRendicaoMinuto() {
		return rendicaoMinuto;
	}

	public void setRendicaoMinuto(Integer rendicaoMinuto) {
		this.rendicaoMinuto = rendicaoMinuto;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public AreaOrganizacional getAreaOrganizacional() {
		return areaOrganizacional;
	}

	public void setAreaOrganizacional(AreaOrganizacional areaOrganizacional) {
		this.areaOrganizacional = areaOrganizacional;
	}

	public Integer getAno() {
		return ano;
	}

	public void setAno(Integer ano) {
		this.ano = ano;
	}

	public Integer getMes() {
		return mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	public EscalaTipo getEscalaTipo() {
		return escalaTipo;
	}

	public void setEscalaTipo(EscalaTipo escalaTipo) {
		this.escalaTipo = escalaTipo;
	}


	
	
}
