package com.moveltrack.reactbackend.model;
// Generated 23/07/2018 04:54:41 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Crime generated by hbm2java
 */
@Entity
public class Crime implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(columnDefinition="serial")
	private Integer id;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	private String enquadramentoPenal;
	private String narrativa;
	private String numeroBoTco;
	
	@JsonIgnore
	@ManyToOne
	private Operacao operacao;
	
	public Operacao getOperacao() {
		return operacao;
	}
	public void setOperacao(Operacao operacao) {
		this.operacao = operacao;
	}

	
	
	
	public String getEnquadramentoPenal() {
		return enquadramentoPenal;
	}
	public void setEnquadramentoPenal(String enquadramentoPenal) {
		this.enquadramentoPenal = enquadramentoPenal;
	}
	public String getNarrativa() {
		return narrativa;
	}
	public void setNarrativa(String narrativa) {
		this.narrativa = narrativa;
	}
	public String getNumeroBoTco() {
		return numeroBoTco;
	}
	public void setNumeroBoTco(String numeroBoTco) {
		this.numeroBoTco = numeroBoTco;
	}
	
	


}
