package com.moveltrack.reactbackend.model;
// Generated 23/07/2018 04:54:41 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Curriculo generated by hbm2java
 */
@Entity
@Table(name = "curriculo", schema = "public")
public class Curriculo implements java.io.Serializable {

	private int id;
	private String observacao;
	private Date data;
	private String endereco;
	private String trabalhoAtual;
	private Serializable telefones;
	private Set<Experiencia> experiencias = new HashSet<Experiencia>(0);
	private Set<Curso> cursos = new HashSet<Curso>(0);
	private Set<Idioma> idiomas = new HashSet<Idioma>(0);
	private Set<Habilidade> habilidades = new HashSet<Habilidade>(0);
	private Set<Formacao> formacaos = new HashSet<Formacao>(0);

	public Curriculo() {
	}

	public Curriculo(int id, String observacao, Date data, String endereco, String trabalhoAtual) {
		this.id = id;
		this.observacao = observacao;
		this.data = data;
		this.endereco = endereco;
		this.trabalhoAtual = trabalhoAtual;
	}

	public Curriculo(int id, String observacao, Date data, String endereco, String trabalhoAtual,
			Serializable telefones, Set<Experiencia> experiencias, Set<Curso> cursos, Set<Idioma> idiomas,
			Set<Habilidade> habilidades, Set<Formacao> formacaos) {
		this.id = id;
		this.observacao = observacao;
		this.data = data;
		this.endereco = endereco;
		this.trabalhoAtual = trabalhoAtual;
		this.telefones = telefones;
		this.experiencias = experiencias;
		this.cursos = cursos;
		this.idiomas = idiomas;
		this.habilidades = habilidades;
		this.formacaos = formacaos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "observacao", nullable = false)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data", nullable = false, length = 29)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "endereco", nullable = false)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "trabalhoAtual", nullable = false)
	public String getTrabalhoAtual() {
		return this.trabalhoAtual;
	}

	public void setTrabalhoAtual(String trabalhoAtual) {
		this.trabalhoAtual = trabalhoAtual;
	}

	@Column(name = "telefones")
	public Serializable getTelefones() {
		return this.telefones;
	}

	public void setTelefones(Serializable telefones) {
		this.telefones = telefones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "curriculo")
	public Set<Experiencia> getExperiencias() {
		return this.experiencias;
	}

	public void setExperiencias(Set<Experiencia> experiencias) {
		this.experiencias = experiencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "curriculo")
	public Set<Curso> getCursos() {
		return this.cursos;
	}

	public void setCursos(Set<Curso> cursos) {
		this.cursos = cursos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "curriculo")
	public Set<Idioma> getIdiomas() {
		return this.idiomas;
	}

	public void setIdiomas(Set<Idioma> idiomas) {
		this.idiomas = idiomas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "curriculo")
	public Set<Habilidade> getHabilidades() {
		return this.habilidades;
	}

	public void setHabilidades(Set<Habilidade> habilidades) {
		this.habilidades = habilidades;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "curriculo")
	public Set<Formacao> getFormacaos() {
		return this.formacaos;
	}

	public void setFormacaos(Set<Formacao> formacaos) {
		this.formacaos = formacaos;
	}

}
