package com.moveltrack.reactbackend.model;
// Generated 23/07/2018 04:54:41 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.springframework.data.annotation.Transient;

/**
 * EscalaTipo generated by hbm2java
 */
@Entity

public class EscalaTipo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(columnDefinition="serial")
	private Integer id;
	
	private Integer horasDeTrabalho1;
	private Integer horasDeDescanso1;
	private Integer horasDeTrabalho2;
	private Integer horasDeDescanso2;
	
	


	private String descricao;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getHorasDeTrabalho1() {
		return horasDeTrabalho1;
	}

	public void setHorasDeTrabalho1(Integer horasDeTrabalho1) {
		this.horasDeTrabalho1 = horasDeTrabalho1;
	}

	public Integer getHorasDeDescanso1() {
		return horasDeDescanso1;
	}

	public void setHorasDeDescanso1(Integer horasDeDescanso1) {
		this.horasDeDescanso1 = horasDeDescanso1;
	}

	public Integer getHorasDeTrabalho2() {
		return horasDeTrabalho2;
	}

	public void setHorasDeTrabalho2(Integer horasDeTrabalho2) {
		this.horasDeTrabalho2 = horasDeTrabalho2;
	}

	public Integer getHorasDeDescanso2() {
		return horasDeDescanso2;
	}

	public void setHorasDeDescanso2(Integer horasDeDescanso2) {
		this.horasDeDescanso2 = horasDeDescanso2;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}



	

	
	

	


}
