package com.moveltrack.reactbackend.model;
// Generated 23/07/2018 04:54:41 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Experiencia generated by hbm2java
 */
@Entity
@Table(name = "experiencia", schema = "public")
public class Experiencia implements java.io.Serializable {

	private int id;
	private Curriculo curriculo;
	private String descricao;
	private String empresa;
	private Date inicio;
	private Date fim;

	public Experiencia() {
	}

	public Experiencia(int id, String descricao, String empresa) {
		this.id = id;
		this.descricao = descricao;
		this.empresa = empresa;
	}

	public Experiencia(int id, Curriculo curriculo, String descricao, String empresa, Date inicio, Date fim) {
		this.id = id;
		this.curriculo = curriculo;
		this.descricao = descricao;
		this.empresa = empresa;
		this.inicio = inicio;
		this.fim = fim;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "curriculo_id")
	public Curriculo getCurriculo() {
		return this.curriculo;
	}

	public void setCurriculo(Curriculo curriculo) {
		this.curriculo = curriculo;
	}

	@Column(name = "descricao", nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "empresa", nullable = false)
	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inicio", length = 29)
	public Date getInicio() {
		return this.inicio;
	}

	public void setInicio(Date inicio) {
		this.inicio = inicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fim", length = 29)
	public Date getFim() {
		return this.fim;
	}

	public void setFim(Date fim) {
		this.fim = fim;
	}

}
