package com.moveltrack.reactbackend.model;
// Generated 23/07/2018 04:54:41 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Idioma generated by hbm2java
 */
@Entity
@Table(name = "idioma", schema = "public")
public class Idioma implements java.io.Serializable {

	private int id;
	private Curriculo curriculo;
	private String descricao;
	private String nivel;

	public Idioma() {
	}

	public Idioma(int id, String descricao, String nivel) {
		this.id = id;
		this.descricao = descricao;
		this.nivel = nivel;
	}

	public Idioma(int id, Curriculo curriculo, String descricao, String nivel) {
		this.id = id;
		this.curriculo = curriculo;
		this.descricao = descricao;
		this.nivel = nivel;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "curriculo_id")
	public Curriculo getCurriculo() {
		return this.curriculo;
	}

	public void setCurriculo(Curriculo curriculo) {
		this.curriculo = curriculo;
	}

	@Column(name = "descricao", nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "nivel", nullable = false)
	public String getNivel() {
		return this.nivel;
	}

	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

}
