package com.moveltrack.reactbackend.model;
// Generated 23/07/2018 04:54:41 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Escala generated by hbm2java
 */
@Entity
public class Plantao implements java.io.Serializable {
	
	
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(columnDefinition="serial")
	private int id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	private Pessoa pessoa;
	
	@ManyToOne
	private Escala escala;
	
    @Enumerated(EnumType.STRING)
	private EscalaEquipeSigla sigla;
	
	@Temporal(TemporalType.TIMESTAMP)
	private Date inicioExpediente;
	
	@Temporal(TemporalType.TIMESTAMP)
	private Date fimExpediente;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Pessoa getPessoa() {
		return pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public Escala getEscala() {
		return escala;
	}

	public void setEscala(Escala escala) {
		this.escala = escala;
	}

	public Date getInicioExpediente() {
		return inicioExpediente;
	}

	public void setInicioExpediente(Date inicioExpediente) {
		this.inicioExpediente = inicioExpediente;
	}

	public Date getFimExpediente() {
		return fimExpediente;
	}

	public void setFimExpediente(Date fimExpediente) {
		this.fimExpediente = fimExpediente;
	}

	public EscalaEquipeSigla getSigla() {
		return sigla;
	}

	public void setSigla(EscalaEquipeSigla sigla) {
		this.sigla = sigla;
	}

	

}
